Updated Damage System
Wolkenfarmer/Space-Invader pull request #6
Opened 2020-12-28 18:55 UTC by Wolkenfarmer

Bullet damage = its health;
InflictDamage now always inflicts damage on the other object;
object kill cycle is now separated from the damge cycle -> dead object can inflict its last damage;
added body damage for space ships;
other minor changes (set references for prefabs etc)

2020-12-28 23:34 UTC, abc013 requested changes
Works ingame, looks good to me otherwise. :+1: 

~It would be nice to also get bullet-bullet collision in here, but you don't have to.~

2020-12-28 23:34 UTC, abc013 commented on Assets/Scripts/Bullets/BulletBehaviorScript.cs
> +		}
Can you please remove the brackets? This is a one line statement.

Also, some spaces smuggled themselves in ;).

2020-12-28 23:34 UTC, abc013 commented on Assets/Scripts/IDamageableObject.cs
> +
Please reduce down to one line.

2020-12-28 23:34 UTC, abc013 commented on Assets/Scripts/Spaceships/SpaceShipBehaviorScript.cs
> +    }
Again some spaces in here.

2020-12-28 23:34 UTC, abc013 commented on Assets/Scripts/GameBehaviorScript.cs
> +	public static readonly List<GameObject> enemies = new List<GameObject>();
why is this `public static`?

2020-12-28 23:34 UTC, abc013 commented on Assets/Scripts/Bullets/BulletBehaviorScript.cs
> +			setDamage(pHealth);
Checking this every tick is not quite necessary: you can check this when actually damaging the object in `OnCollisionEnter2D`

2020-12-28 23:34 UTC, abc013 commented on Assets/Scripts/Spaceships/DefaultEnemyBehaviorScript.cs
> +        }
Checking this every tick is not quite necessary: you can check this when actually damaging the object in `OnCollisionEnter2D`

2020-12-28 23:34 UTC, abc013 commented on Assets/Scripts/Bullets/BulletBehaviorScript.cs
> +			setDamage(pHealth);
I see know why you actually did this. I don't like that we actually have to do that. It would be nice to have a comment telling why we actually do this in the update method.

2020-12-28 23:34 UTC, abc013 commented on Assets/Scripts/Spaceships/DefaultEnemyBehaviorScript.cs
> +        }
I see know why you actually did this. I don't like that we actually have to do that. It would be nice to have a comment telling why we actually do this in the update method.

2020-12-28 23:36 UTC, abc013 commented on Assets/Scripts/Bullets/BulletBehaviorScript.cs
> +		}
Apparently, there are more `if` statements with only one line of code. You actually used an `if` statement without braces further below, so it would be nice to set on one specific style.

2020-12-28 23:55 UTC, Wolkenfarmer commented on Assets/Scripts/Bullets/BulletBehaviorScript.cs
> +			setDamage(pHealth);
This is necessary in order for the dead object to inflict its last damage to the other object, if it would be killed first.

2020-12-28 23:55 UTC, Wolkenfarmer commented on Assets/Scripts/Spaceships/DefaultEnemyBehaviorScript.cs
> +        }
This is necessary in order for the dead object to inflict its last damage to the other object, if it would be killed first.

2020-12-28 23:55 UTC, Wolkenfarmer commented on Assets/Scripts/GameBehaviorScript.cs
> +	public static readonly List<GameObject> enemies = new List<GameObject>();
Changed back

2020-12-29 00:03 UTC, abc013 approved these changes

2020-12-29 00:04 UTC, merged